In [12]:
import test_algo
import numpy as np

In [30]:
pos_player = [1,0] # player is in first row of field
pos_ball = [7,0] # ball is second to last row
pos_goal = [0,3] # goas is one row above the field
pos_goal2 = [0,4] # on 2 sqares 

In [31]:
#initialize

def the_grid(pos_ball, pos_player, pos_goal):
    grid = np.zeros((9,8))
    grid[pos_ball[0]][pos_ball[1]] = 44
    grid[pos_player[0]][pos_player[0]] = 66
    grid[pos_goal[0]][pos_goal[1]] = 55
    grid[pos_goal2[0]][pos_goal2[1]] = 55
    print(grid)

the_grid(pos_ball, pos_player, pos_goal)

[[ 0.  0.  0. 55. 55.  0.  0.  0.]
 [ 0. 66.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [44.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]]


In [32]:
while not pos_player[0] == pos_ball[0]: 
    test_algo.go_down(pos_player)


go_down


IndexError: index -15 is out of bounds for axis 0 with size 10